spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888



#server.port=8082

#spring.data.mongodb.uri=mongodb://localhost:27017/user_service
#spring.data.mongodb.database=user_service
#spring.datasource.url=jdbc:mysql://localhost:3306/user_service
#spring.datasource.username=root
#spring.datasource.password=Rawat@123

#jpa configuration
#spring.jpa.show-sql=true

#for creating and update schemas and tables
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

