
services:
#  mysql-db:
#    image: mysql:8.0
#    container_name: mysql-db
#    restart: unless-stopped
#    environment:
#      MYSQL_ROOT_PASSWORD: Rawat@123
#      MYSQL_DATABASE: ecomm_microservices
#    ports:
#      - "3307:3306"
#    networks:
#      - backend
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin
#    restart: unless-stopped
#    environment:
#      PMA_HOST: mysql-db
#      PMA_USER: root
#      PMA_PASSWORD: Rawat@123
#    ports:
#      - "8081:80"
#    networks:
#      - backend

#  ecommerce-app:
#    image: sauravkumarr/ecommerce-microservices
#    container_name: ecommerce-app
#    restart: unless-stopped
#    depends_on:
#      - mysql-db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ecomm_microservices
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: Rawat@123
#    ports:
#      - "8080:8080"   # Expose your app on localhost:8080
#    networks:
#      - backend

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # RabbitMQ broker port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend
#  zipkin:
#    image: openzipkin/zipkin
#    container_name: zipkin
#    ports:
#      - "9411:9411"
#    networks:
#      - backend
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    container_name: keycloak
    # The 'start-dev' argument goes here
    command: start-dev
    # Environment variables from your -e flags
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    # Port mapping from your -p flag (127.0.0.1 limits access to localhost only)
    ports:
      - "8443:8080"
    networks:
      - backend
    volumes:
      - ./keycloak-data:/opt/keycloak/data/h2

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend

networks:
  backend:
    driver: bridge
#
#volumes:
#  mysql_data: