spring:
  application:
   name: producer
  cloud:
    function:
      definition: sendRiderLocation
    stream:
      bindings:
        sendRiderLocation-out-0:
          destination: my-topic
          content-type: application/json
      poller:
        fixed-delay: 1000

      kafka:
        binder:
          brokers: localhost:9092

#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#  cloud:
#    function:
#      definition: uppercase
#      web:
#        path: /uppercase
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.add.type.headers: false
